config/routes.rb
StaticDynamic::Application.routes.draw do

  get "sessions/new"

	post 'users/mobile'	
	post 'users/mobile_get'	
	
	resources :users do
		member do
			get :following, :followers
		end
	end
	
	resources :sessions, :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy]  
	resources :password_resets
	resources :jobseekers
	
	post 'jobs/mobile_post'
	post 'jobs/mobile_get'
	resources :jobs
	  
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	get '/signout', :to => 'sessions#destroy' 
  
  get '/contact', :to => 'pages#contact'	#book says to use 'match' in place of get 
	get '/about', :to => 'pages#about'	#but troubleshooting(integration tests))say 
	get '/help', :to => 'pages#help'	#use 'get' so...
	
	get 'jobseekers/download_cv'
	get 'jobseekers/view_cv'
	
	
	root :to => 'pages#home'
  
  

  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>

	<div id="error_explanation">
		<h2><%= pluralize(object.errors.count, "error") %> prohibited this user from being saved:</h2>
		<p>There were problems with the following fields:</p>
	
		<ul>
			<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	
	</div>
	
<% end %>

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<table class="microposts" summary="User microposts">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	</table>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
	<td class="gravatar">
		<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	</td>
	<td class="micropost">
		<span class="user">
		<%= link_to feed_item.user.first_name, feed_item.user %>
		</span>
		<span class="content"><%= feed_item.content %></span><br />
		<span class="timestamp">
			<i>Posted <%= time_ago_in_words(feed_item.created_at) %> ago.</i>
		</span>
	</td>

	<% if current_user?(feed_item.user) %>
		<td>
			<%= link_to "delete", feed_item, :method => :delete, :confirm => "You sure?", :title => feed_item.content %>
		</td>
	<% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.text_area :content %>
	</div>
	
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/shared/_profile_fields.html.erb
<h1></h1>
<%= render 'shared/error_messages', :object => f.object %>
	
	<h4 align="right"><a href="#upload_cv">upload your cv</a></h4>
	
	<fieldset>
	<%= label_tag(:dob, "Birthday:") %><br>
	<div class="select_border" ><%= f.date_select(:dob,:start_year => Date.current.year - 18, :end_year => 1939) %></div>
	</fieldset><br>
	
	<fieldset>
	<div class="actions">
    
    <%= f.label :sex, "Gender:" %><br>
    <%= f.radio_button :sex, "female",:required=>"required" %>
    <%= f.label :sex, "Female", :value=>"female",:id=>"label_roles" %>
    <%= f.radio_button :sex, "male",:required=>"required" %>
    <%= f.label :sex, "Male", :value=>"male",:id=>"label_roles" %>
	</div>
	</fieldset>
	
	    
	<fieldset>
		<%= f.label :location, "Location:" %><br>
		<%= f.text_field :location, :placeholder=> "prefered location for a job e.g gulu", :required=> "true"%>
	</fieldset><br>
	
	<fieldset>
		<%= f.label :phone, "Phone:" %><br>
		<%= f.text_field :phone, :placeholder=> "for contacting you", :required=> "false"%>
	</fieldset><br>

	
	<fieldset>

		<% @qualification = [['None', 'None'],['O level', 'O level'],['A level', 'A level'],['Certificate', 'Certificate'],['Diploma', 'Diploma'],['Degree', 'Degree'],['Masters', 'Masters'],['PhD holder', 'PhD holder']] %>
		
		<%= label_tag(:qualification, "Qualification:") %><br>
		<div class="select_border"><%= f.select :qualification, @qualification %></div>
	</fieldset><br>
	
	<fieldset>

		<% @field = [['None', 'None'], ['Accounting/Finance/Insurance', 'Accounting/Finance/Insurance'], ['Administrative/Clerical/Office', 'Administrative/Clerical/Office'], ['Agriculture/Forestry/Fishing', 'Agriculture/Forestry/Fishing'], ['Banking', 'Banking'], ['Building Construction/Skilled Trades', 'Building Construction/Skilled Trades'], ['Business/Strategic Management', 'Business/Strategic Management'], ['Creative/Design/Architectural', 'Creative/Design/Architectural'], ['Customer Support/Client Care', 'Customer Support/Client Care'], ['Editorial/Writing', 'Editorial/Writing'], ['Education', 'Education'], ['Engineering', 'Engineering'], ['Entertainment Venues and Theaters', 'Entertainment Venues and Theaters'], ['Food Services/Hospitality', 'Food Services/Hospitality'], ['Government and Military', 'Government and Military'], ['Hotels and Lodging', 'Hotels and Lodging'], ['Human Resources', 'Human Resources'], ['Installation/Maintenance/Repair', 'Installation/Maintenance/Repair'], ['IT/Software Development', 'IT/Software Development'], ['Legal', 'Legal'], ['Logistics/Transportation', 'Logistics/Transportation'], ['Management Consulting Services', 'Management Consulting Services'], ['Manufacturing', 'Manufacturing'], ['Marketing/Adevertising', 'Marketing/Adevertising'], ['Medical/Health', 'Medical/Health'], ['Printing and Publishing', 'Printing and Publishing'], ['Project/Program Management', 'Project/Program Management'], ['Public Relations', 'Public Relations'], ['Real Estate / Property Management', 'Real Estate / Property Management'], ['Security/Protective Services', 'Security/Protective Services'], ['Sales', 'Sales']] %>
		
		<%= label_tag(:field, "Field:") %><br>
		<div class="select_border"><%= f.select :field, @field %></div>
	</fieldset><br>
		    
	<fieldset>
		<%= f.label :experience, "Experience:" %><br>
		<%= f.text_field :experience, :placeholder=> "your experience in years", :required=> "true"%>
	</fieldset><br>
	<a name="upload_cv">	
	<fieldset>
		<%= f.label :cv, "Curriculam Vitae (must be a pdf):" %><br>
	  <%= f.file_field :cv, :accept=>"application/pdf" %>
	</fieldset></a><br>
		
	<fieldset>
		<%= f.label :summary, "Summary:" %><br>
		<%= f.text_area :summary, :placeholder=> "short summary about you...", :required=> "false"%><br>
	</fieldset><br>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
	<div class="stats">
		<table summary="User stats">
			<tr>
				<td>
					<a href="<%= following_user_path(@user) %>">
						<span id="following" class="stat">
							<%= @user.following.count %> following
						</span>
					</a>
				</td>
				
				<td>
					<a href="<%= followers_user_path(@user) %>">
						<span id="followers" class="stat">
							<%= pluralize(@user.followers.count, "follower") %>
						</span>
					</a>
				</td>
			</tr>
		</table>
	</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user, :size => 30 %>
		<span class="user_name">
			<%= current_user.first_name %><br />
		</span>
		<span class="microposts">
			<%= pluralize(current_user.microposts.count, "micropost") %>
		</span>
	</a>
</div>