config/routes.rb
StaticDynamic::Application.routes.draw do

  get "sessions/new"

	post 'users/mobile'	
	post 'users/mobile_get'	
	
	resources :users do
		member do
			get :following, :followers
		end
	end
	
	resources :sessions, :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy]  
	resources :password_resets
	resources :jobseekers
	
	post 'jobs/mobile_post'
	post 'jobs/mobile_get'
	resources :jobs
	  
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	get '/signout', :to => 'sessions#destroy' 
  
  get '/contact', :to => 'pages#contact'	#book says to use 'match' in place of get 
	get '/about', :to => 'pages#about'	#but troubleshooting(integration tests))say 
	get '/help', :to => 'pages#help'	#use 'get' so...
	
	get 'jobseekers/download_cv'
	get 'jobseekers/view_cv'
	
	
	root :to => 'pages#home'
  
  

  

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<h4><p>Job radar is an application that helps get employers' job advertisments out to the masses while giving jobseekers job feeds specific to their preferences. </p></h4>

app/views/pages/contact.html.erb
<h1>Contact</h1><br>
<h4><p>
Contact: <a>jobradar@gmail.com</a>
				 
</p>
</h4>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
Get help on Ruby on Rails Tutorial at the
<a href="http://railstutorial.org/help">Rails Tutorial help page</a>
To get help on this sample app, see the
<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
	<% if current_user.role == "jobseeker" %>
		<%#
		<%#= form_tag jobs_path, :method=>'get' do %>
		<%#	<p align="center">
				<%= text_field_tag :search %>
		<%#		<%= submit_tag "Search All", :id=>"search_btn", :name=>nil %>
		<%#	</p> %>
			
			<div>
			<h1>Available Jobs according to your profile</h1>
				<%if @jobs%>
					<ul>
						<li>						
							<% @jobs.each do |job|%>
								<div>
								<h4>
								<%= link_to job.title, job %><h4>
								<div class = "dets">
								<%=job.job_type%> | <%= job.location %> | Deadline: <%= job.deadline.to_date %>
								</div>
								<hr>
								</div>
							<% end %>
						</li>
					</ul>
				<%elsif%>
					<h1>Sorry, no jobs listing available. Try editing your profile to get a new jobs listing.</h1>
				<%end%>
			</div>
		<%#<% end %>
		
	<% elsif current_user.role == "employer" %>
		
	<%#	<%= form_tag jobseekers_path, :method=>'get' do %>
	<%#		<p align="center">
	<%#			<%= text_field_tag :search %>
	<%#			<%= submit_tag "Search All", :id=>"search_btn", :name=>nil %>
	<%#		</p>
	<%#	<% end %>
		<div>
		
		<%#= link_to "mobileget", users_mobile_get_path(:Last_user => 0, :Employer => 3 ), :method => 'post'%><br>
			<h1>Job seekers that qualify for your posted jobs</h1>
				<%if @seekers%>
					<ul>
						<li>
						<h4>
					<% @seekers.each do |details| %>
						<% details.each do |detail| %>
							<% @users = detail.user_id %>
							<% @user = User.find(@users) %>
							<% name1 = @user.first_name %>
							 <% name2 = @user.last_name%>
							<%= link_to "#{name1} #{name2}", user_path(detail.user_id) %><br>
						<% end %>
				<% end %>
						</h4>
						</li>
					</ul>						
				<%else%>
					<h1>It seems we don't have any jobseekers that match, check back in a while... or post some jobs if you haven't already</h1>
				<%end%>
			</div>
		
	<% end %>
<div id="list">

	
	<ul id="list_items">
		<li>
			
		</li>
</div>
<% else %>
	<div class="splash">
        <h1 class="splash-head">JOB RADAR</h1>
        <p class="splash-subhead">
            Every Job At Your Finger Tips 
        </p>
        <p id="splash_btn">
         <%= link_to "Sign up now!", signup_path, :class=>"splash_btn" %>
        </p>
    </div>
	
<% end %>

app/views/pages/profile.html.erb
<h1>Create your profile</h1>

<%= form_for(@jobseeker) do |f| %>
	<%= render 'shared/profile_fields', :f => f %><br><br><br><br>
	<fieldset>
	<div class="actions">
		<%= f.submit "Save Profile", :id=>"edit_profile_btn" %>
	</div>
	</fieldset>
<% end %>