config/routes.rb
StaticDynamic::Application.routes.draw do

  get "sessions/new"

	post 'users/mobile'	
	post 'users/mobile_get'	
	
	resources :users do
		member do
			get :following, :followers
		end
	end
	
	resources :sessions, :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy]  
	resources :password_resets
	resources :jobseekers
	
	post 'jobs/mobile_post'
	post 'jobs/mobile_get'
	resources :jobs
	  
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	get '/signout', :to => 'sessions#destroy' 
  
  get '/contact', :to => 'pages#contact'	#book says to use 'match' in place of get 
	get '/about', :to => 'pages#about'	#but troubleshooting(integration tests))say 
	get '/help', :to => 'pages#help'	#use 'get' so...
	
	get 'jobseekers/download_cv'
	get 'jobseekers/view_cv'
	
	
	root :to => 'pages#home'
  
  

  

end

app/models/jobseeker.rb
# == Schema Information
#
# Table name: jobseekers
#
#  id            :integer          not null, primary key
#  user_id       :integer
#  dob           :date
#  sex           :string(255)
#  location      :string(255)
#  phone         :string(255)
#  qualification :string(255)
#  experience    :string(255)
#  field         :string(255)
#  cv_type       :string(255)
#  summary       :text
#  created_at    :datetime
#  updated_at    :datetime
#

class Jobseeker < ActiveRecord::Base
		
		#add protected_attributes gem to the Gemfile
		attr_accessible :dob,#1992-09-12
										:sex,#male,female
										:location,#kampala
										:phone,#no.
										:qualification,#degeree
										:experience,#years{1,2,3}
										:field,#computer science
										:cv_type,#pdf
										:summary#abot you
										
		belongs_to :user
		
		validates_presence_of :dob, :sex, :location, :phone, :qualification, :experience, :field
		validates :summary, :length => {:maximum=>400}
		validates :phone, :length => {:maximum=>13, :minimum=>10}
		validates :experience, :length => {:maximum=>2, :minimum=>1}
		validates :experience, :numericality => { :greater_than_or_equal_to => 0 }
		# 'only_integer' uses regx: /\A[+-]?\d+\Z/
		validates_numericality_of :phone, :experience, :only_integer => true
		validate :over_15
		validate :cv_format

		
		
	def over_15
		if dob + 15.years >= Date.today
		  errors.add(:dob,": your age can't be under 15")
		end
	end
	

	def cv_format
		errors.add(:cv_type, "must be a pdf") if self.cv_type != "application/pdf"
	end
		
		#returns jobseeker details starting with most recently added ones
		default_scope :order => 'jobseekers.created_at DESC'
		
end

app/controllers/jobseekers_controller.rb
class JobseekersController < ApplicationController
	#authenticate is in sessions_helper(global sccess) &  denies access unless signed in.(also stores attempted url)
	before_filter :authenticate, :only => [:create, :destroy, :edit, :update]
	
	#shows all jobseeker details, in a list or something
	def index
		
	end
	
	def show
		@action = params[:id].to_s
		@user = current_user.id
		@jobseeker = Jobseeker.find_by!(:user_id => @user)
		
		if File.exist?(Rails.root.join('public', 'uploads', @jobseeker.id.to_s ))
			
			if @action == 'download_cv'
				#send file snds the pdf for downloading
				send_file Rails.root.join('public', 'uploads', @jobseeker.id.to_s ), :type=>"application/pdf", :x_sendfile=>true
			
			elsif @action == 'view_cv'
				#sends file to user but for renering in the browser
				send_file Rails.root.join('public', 'uploads', @jobseeker.id.to_s ),:disposition => 'inline', :type=>"application/pdf", :x_sendfile=>true
				
			else
				redirect_to user_path(current_user)
			end
			
  	else
  		flash[:notice]="you haven't uploaded a cv yet! Upload one."
			render 'edit'
  	end
				
	end
	
	def new
    @jobseeker = current_user.build_jobseeker
  	@title = "Create Your Profile"
	end
	
	#allows creation of jobseeker details on signup/posting them
	def create
		@user = current_user#use it for naming the cv
		
		#build holds the entered details but does not save to the database.
		@jobseeker = current_user.build_jobseeker(params[:jobseeker])
		upload_cv
				
		#if saving the details to the db returns true...else...
		if @jobseeker.save
			flash[:success] = "success! your profile information has been saved."			
			redirect_to current_user
		else
			render 'new'
		end
	end
	
	#directs to update if its an edit and to save profile if its the first time
	def edit
			@user = User.find(params[:id])
			@jobseeker1 = Jobseeker.find_by(:user_id => @user.id)

		if @jobseeker1
			@jobseeker = @jobseeker1
			@title = "Edit Profile"
		else
			flash[:notice] = "we don't have your profile yet, create one!"
			#don't use render 'new' because it refers to @jobseeker from this action(and in this section of action, its nil.)
			redirect_to new_jobseeker_path
		end
		
	end
	
	#for updating attributes
	def update
		@user = current_user#use it for naming the cv
		@jobseeker = Jobseeker.find(params[:id])
		upload_cv
		
		if @jobseeker.update_attributes(params[:jobseeker])
			flash[:success] = "profile updated."
			redirect_to current_user
		else
			@title = "Edit user"
			render 'edit'
		end
	end
	
	def destroy
		
	end
	
	def upload_cv
		uploaded_io = params[:jobseeker][:cv]
		
		#if a file has been uploaded
		if uploaded_io
		
			#convert its type into string
			@type = uploaded_io.content_type.to_s
			
			#save it if the type is pdf
			if @type == "application/pdf"
				
				File.open(Rails.root.join('public', 'uploads', @user.id.to_s), 'wb') do |file|
						file.write(uploaded_io.read)
				end
				
				#make cv_type = 'application/pdf'(so it passes validation)
				@jobseeker.cv_type = @type
				
			else
				#return an error o trying to save wrong type(active record returns the error)
				@jobseeker.cv_type = @type
			end
		else
			#nothing is uploaded, ensure validations passes
			@jobseeker.cv_type = "application/pdf"
		end
  end
	
end

app/views/jobseekers/_jobseeker.html.erb
<h4>
	<span class="content">
		
		<% now = Time.now.utc.to_date %>
		<%= label_tag(:dob, "Age:") %>
		<h4><%= now.year - @user.jobseeker.dob.year %> years old</h4><br>

		<%= label_tag(:sex, "Gender:") %>
		<h4><%= @user.jobseeker.sex %></h4><br>

		<%= label_tag(:location, "Prefered job location:") %>
		<h4><%= @user.jobseeker.location %></h4><br>
		
		<%= label_tag(:phone, "Phone number:") %>
		<h4><%= @user.jobseeker.phone %></h4><br>
		
		<%= label_tag(:qualification, "Qualification:") %>
		<h4><%= @user.jobseeker.qualification %></h4><br>
		
		<%= label_tag(:field, "Field:") %>
		<h4><%= @user.jobseeker.field %></h4><br>

		<%# 'pluralize' - helper method: makes plurals of a singular word if the supplied integer value is greater than 1 %>
		<%= label_tag(:experience, "Your experience in the field:") %>
		<h4><%= pluralize(@user.jobseeker.experience,"year") %></h4><br>
		
		<%#view_cv is an action in jobseekers controller%>
		<h4><%= link_to "Veiw your CV", jobseekers_view_cv_path, :target => "_blank" %> <h3>OR</h3> <%= link_to "Download it", jobseekers_download_cv_path, :target => "_blank" %></h4><br>
		
		<%= label_tag(:summary, "About you:") %>
		<h4><%= @user.jobseeker.summary %></h4><br>
		<%%>	
		
	</span>
</h4>

app/views/jobseekers/edit.html.erb
<h1>Edit your profile</h1>

<%= form_for(@jobseeker) do |f| %>
	<%= render 'shared/profile_fields', :f => f %><br><br><br><br>
	<fieldset>
	<div class="actions">
		<%= f.submit "Update Profile", :id=>"update_profile_btn" %>
	</div>
	</fieldset>
<% end %>

app/views/jobseekers/index.html.erb
<ul class="jobs">
	<li>
		<h4>
			<%= link_to @job.title, @job %>			
		</h4>
	</li>
</ul>

app/views/jobseekers/new.html.erb
<h1>Save your profile</h1>

<%= form_for(@jobseeker) do |f| %>
	<%= render 'shared/profile_fields', :f => f %><br><br><br><br>
	<fieldset>
	<div class="actions">
		<%= f.submit "Save Profile", :id=>"edit_profile_btn" %>
	</div>
	</fieldset>
<% end %>