config/routes.rb
StaticDynamic::Application.routes.draw do

  get "sessions/new"

	post 'users/mobile'	
	post 'users/mobile_get'	
	
	resources :users do
		member do
			get :following, :followers
		end
	end
	
	resources :sessions, :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy]  
	resources :password_resets
	resources :jobseekers
	
	post 'jobs/mobile_post'
	post 'jobs/mobile_get'
	resources :jobs
	  
  
  get "pages/home"
  get "pages/contact"
  get "pages/about"
  get "pages/help"
  

  get '/signup', :to => 'users#new'
	get '/signin', :to => 'sessions#new'
	get '/signout', :to => 'sessions#destroy' 
  
  get '/contact', :to => 'pages#contact'	#book says to use 'match' in place of get 
	get '/about', :to => 'pages#about'	#but troubleshooting(integration tests))say 
	get '/help', :to => 'pages#help'	#use 'get' so...
	
	get 'jobseekers/download_cv'
	get 'jobseekers/view_cv'
	
	
	root :to => 'pages#home'
  
  

  

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
		<li><a href="https://www.facebook.com/bibangamba">Facebook</a></li>
		<li><a href="https://www.twitter.com/bibangamba">Twitter</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
		<%= link_to logo, root_path %>
		<nav class="round">
			<ul>
			<li><%= link_to "Home", root_path %></li>

			<% if signed_in? %>
				
				<% if current_user.admin=="yes"%>
					<li><%= link_to "Users", users_path %></li>
				<% end %>
				
				<%if current_user.role=="jobseeker"%>
					<li><%= link_to "Profile", current_user %></li>
					<li><%= link_to "Edit Profile", edit_jobseeker_path(current_user) %></li>
				<%elsif current_user.role=="employer"%>
					<li><%= link_to "Post Job", new_job_path %></li>				
					<li><%= link_to "Posted Jobs", jobs_path %></li>					
				<% end %>
				
				<li><%= link_to "Settings", edit_user_path(current_user) %></li>
				
				
			<% end %>

			<li><%= link_to "Help", help_path %></li>
			
			<% if signed_in? %>
				<li><%= link_to "Sign out", signout_path, :method => :get %></li>
			<% else %>
				<li><%= link_to "Sign in", signin_path %></li>
			
			<% end %>
		</ul>
		</nav>
</header>

app/views/layouts/_stylesheets.html.erb
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
		<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
		<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
		<%= stylesheet_link_tag 'custom', :media => 'screen' %>
		<%= stylesheet_link_tag 'mobile' if mobile_device? %><!-- mobile_device is a helper mthd in application_controller.rb -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="shortcut icon" href="/images/radar.png">
	<title><%= title %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag :application %>
	</head>
	<body>
		<div class="container">
		<%= render 'layouts/header' %>
		<section class="round">

			<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
			<% end %>

			<%= yield %>

		</section>
		<% if mobile_device? %>
			<%= link_to "Full View", :mobile => 0%>
		<% else %>
			<%#= link_to "Mobile View", :mobile => 1%>
		<%end%>
		
		<%= render 'layouts/footer' %><br>
		<%#= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>